[package]
name = "payas-wasm-model-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"

payas-core-model = { path = "../../payas-core-subsystem/payas-core-model" }
payas-core-model-builder = { path = "../../payas-core-subsystem/payas-core-model-builder" }

payas-wasm-model = { path = "../payas-wasm-model" }
payas-subsystem-model-builder-util = { path = "../../payas-subsystem-util/payas-subsystem-model-builder-util" }

[dev-dependencies]



[lib]
