[package]
name = "payas-deno-model"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql-parser = "4.0.5"
async-graphql-value = "4.0.5"
serde = { version = "1.0.136", features = ["derive"] }
bincode = "1.3.3"

payas-plugin-model-util = { path = "../../payas-plugin-util/payas-plugin-model-util" }
payas-core-model = { path = "../../payas-core-plugin/payas-core-model" }
payas-core-model-builder = { path = "../../payas-core-plugin/payas-core-model-builder" }

[dev-dependencies]



[lib]
