[package]
name = "introspection-resolver"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-graphql-parser.workspace = true
async-graphql-value.workspace = true
async-recursion.workspace = true
futures.workspace = true
serde_json = { workspace = true, features = ["preserve_order"] }
async-trait.workspace = true
tokio.workspace = true

core-resolver = { path = "../../core-subsystem/core-resolver" }
core-model = { path = "../../core-subsystem/core-model" }
core-plugin-shared = { path = "../../core-subsystem/core-plugin-shared" }
common = { path = "../../common" }


[dev-dependencies]

[lib]
doctest = false
