[package]
name = "postgres-rpc-resolver"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
http.workspace = true
serde_json.workspace = true

exo-sql = { path = "../../../libs/exo-sql" }

core-model = { path = "../../core-subsystem/core-model" }
core-resolver = { path = "../../core-subsystem/core-resolver" }
postgres-rpc-model = { path = "../postgres-rpc-model" }
postgres-core-resolver = { path = "../postgres-core-resolver" }
postgres-core-model = { path = "../postgres-core-model" }
rpc-introspection = { path = "../../rpc-introspection" }
common = { path = "../../common" }

[dev-dependencies]

[lib]
doctest = false
