# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      wasm:
        patterns:
          - "wasm-bindgen"
          - "wasm-bindgen-*"
          - "js-sys"
          - "web-sys"
      deno:
        patterns:
          - "deno_*"
          - "node_resolver"
      wasmtime:
        patterns:
          - "wasmtime"
          - "wasi-common"
      async-graphql:
        patterns:
          - "async-graphql-*"
      tracing:
        patterns:
          - "tracing"
          - "tracing-*"
      postgres:
        patterns:
          - "*postgres*"
          - "pg_bigdecimal"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: "npm"
    directories:
      - "/docs"
      - "/playground/lib"
      - "/playground/app"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      css-tooling:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "postcss"
          - "autoprefixer"
      docusaurus:
        patterns:
          - "@docusaurus/*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore
      include: scope
