[package]
name = "payas-parser"
version = "0.1.0"
authors = ["Ramnivas Laddad <ramnivas@payalabs.com>"]
edition = "2018"

[dependencies]
tree-sitter = "0.19.5"
id-arena = "2.2.1"
serde = { version = "1.0.125", features = ["derive"] }
lazy_static = "1.4.0"
codemap = "0.1.3"
codemap-diagnostic = "0.1.1"
anyhow = "1.0"
payas-model = { path = "../payas-model" }

[build-dependencies]
cc="*"

[dev-dependencies]
insta = "1.7.0"

[lib]
