[package]
name = "core-plugin-shared"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde.workspace = true
bincode.workspace = true
thiserror.workspace = true
bytes.workspace = true
tracing.workspace = true
sha2 = "0.10"
base16ct = { version = "0.3.0", features = ["alloc"] }
wildmatch = { workspace = true, features = ["serde"] }

[dev-dependencies]
wasm-bindgen-test.workspace = true
wasm-bindgen-test-macro.workspace = true
multiplatform_test.workspace = true

[lib]
doctest = false
