[package]
name = "core-router"
version.workspace = true
edition.workspace = true
publish = false

[features]
default = []
test-context = []

[dependencies]
thiserror.workspace = true

exo-env = { path = "../../../libs/exo-env" }

core-plugin-shared = { path = "../core-plugin-shared" }
core-plugin-interface = { path = "../core-plugin-interface" }


[lib]
doctest = false
