[package]
name = "postgres-graphql-model"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde.workspace = true
bincode.workspace = true
async-graphql-parser.workspace = true
async-graphql-value.workspace = true
postgres-core-model = { path = "../postgres-core-model" }

core-model = { path = "../../core-subsystem/core-model" }
core-plugin-shared = { path = "../../core-subsystem/core-plugin-shared" }

[dev-dependencies]
wasm-bindgen-test.workspace = true

[lib]
doctest = false
