[package]
name = "deno-model-builder"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-recursion.workspace = true
bincode.workspace = true

core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
subsystem-model-builder-util = { path = "../../subsystem-util/subsystem-model-builder-util" }
deno-model = { path = "../deno-model" }
exo-deno = { path = "../../../libs/exo-deno" }
url.workspace = true
tokio.workspace = true
async-trait.workspace = true
anyhow.workspace = true
futures = "0.3"

deno.workspace = true
deno_core.workspace = true
deno_ast = { workspace = true, features = ["transpiling"] }
deno_graph.workspace = true
deno_npm.workspace = true
deno_virtual_fs.workspace = true
deno_runtime.workspace = true
serde_json.workspace = true

[dev-dependencies]

[lib]
crate-type = ["lib"]
doctest = false
