[package]
name = "postgres-rpc-model"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde.workspace = true

postgres-core-model = { path = "../postgres-core-model" }
core-model = { path = "../../core-subsystem/core-model" }
core-plugin-shared = { path = "../../core-subsystem/core-plugin-shared" }
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }

[dev-dependencies]

[lib]
doctest = false
