[package]
name = "payas-deno-model-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"

payas-core-model = { path = "../../payas-core-plugin/payas-core-model" }
payas-core-model-builder = { path = "../../payas-core-plugin/payas-core-model-builder" }
payas-deno-model = { path = "../payas-deno-model" }
payas-plugin-model-builder-util = { path = "../../payas-plugin-util/payas-plugin-model-builder-util" }

[dev-dependencies]



[lib]
