[package]
name = "postgres-rpc-builder"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
core-model = { path = "../../core-subsystem/core-model" }
postgres-core-model = { path = "../postgres-core-model" }
postgres-rpc-model = { path = "../postgres-rpc-model" }
postgres-core-builder = { path = "../postgres-core-builder" }
core-plugin-shared = { path = "../../core-subsystem/core-plugin-shared" }
core-model-builder = { path = "../../core-subsystem/core-model-builder" }


[dev-dependencies]

[lib]
doctest = false
