[package]
name = "postgres-rest-model"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde.workspace = true
http.workspace = true
matchit = "0.9.0"

common = { path = "../../common" }
exo-sql = { path = "../../../libs/exo-sql" }
core-model = { path = "../../core-subsystem/core-model" }
postgres-core-model = { path = "../postgres-core-model" }
core-plugin-shared = { path = "../../core-subsystem/core-plugin-shared" }
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
[dev-dependencies]

[lib]
doctest = false
