[package]
name = "deno-graphql-model"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-graphql-parser.workspace = true
serde.workspace = true

subsystem-model-util = { path = "../../subsystem-util/subsystem-model-util" }
core-model = { path = "../../core-subsystem/core-model" }
core-plugin-shared = { path = "../../core-subsystem/core-plugin-shared" }

[dev-dependencies]


[lib]
doctest = false
