[package]
name = "deno-graphql-model"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-graphql-parser.workspace = true
async-graphql-value.workspace = true
serde.workspace = true

bincode.workspace = true
subsystem-model-util = { path = "../../subsystem-util/subsystem-model-util" }
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }

[dev-dependencies]


[lib]
doctest = false
