[package]
name = "payas-server-actix"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
actix-web = { version = "4.0.1", default-features = false, features = ["macros"] }
actix-cors = "0.6.1"
actix-files = "0.6.0"
actix-web-httpauth = "0.6.0"
bincode = "1.2.1"
futures = "0.3"
jsonwebtoken = "7.2.0"
serde_json = { version = "1.0", features = ["preserve_order"] }

payas-server-core = { path = "../payas-server-core" }
payas-sql = { path = "../payas-sql" }
payas-model = { path = "../payas-model" }

[[bin]]
name = "clay-server"
path = "src/main.rs"
