[package]
name = "postgres-model-builder-dynamic"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
postgres-builder = { path = "../postgres-builder" }
postgres-model-builder = { path = "../postgres-model-builder" }

[dev-dependencies]

[lib]
crate-type = ["cdylib"]
doctest = false
