[package]
name = "payas-database-model-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
heck = "0.4.0"
bincode = "1.3.3"
serde = { version = "1.0.136", features = ["derive"] }
codemap = "0.1.3"
codemap-diagnostic = "0.1.1"
lazy_static = "1.4.0"
typed-generational-arena = { version = "0.2", features = ["serde"] }
wildmatch = "2.1.0"
thiserror = "1.0.30"

payas-core-model = { path = "../../payas-core-subsystem/payas-core-model" }
payas-core-model-builder = { path = "../../payas-core-subsystem/payas-core-model-builder" }
payas-database-model = { path = "../payas-database-model" }
payas-sql = { path = "../../payas-sql" }



[dev-dependencies]



[lib]
