[package]
name = "wasm-graphql-model"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-graphql-parser.workspace = true
serde.workspace = true

core-model = { path = "../../core-subsystem/core-model" }
core-plugin-shared = { path = "../../core-subsystem/core-plugin-shared" }
subsystem-model-util = { path = "../../subsystem-util/subsystem-model-util" }

[dev-dependencies]


[lib]
doctest = false
